# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarrierRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_address', models.CharField(max_length=256)),
                ('loading_contacts', models.CharField(blank=True, max_length=256)),
                ('landing_address', models.CharField(max_length=256)),
                ('landing_contacts', models.CharField(blank=True, max_length=256)),
                ('cost', models.DecimalField(decimal_places=9, max_digits=16)),
                ('invoice_number', models.CharField(max_length=20)),
                ('invoice_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('delay', models.BooleanField()),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Contractor')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Contractor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Contractor')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Contractor')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Contractor')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Contractor')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='ForwardVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_price', models.DecimalField(decimal_places=9, max_digits=16)),
                ('places_count', models.IntegerField()),
                ('weight', models.FloatField()),
                ('destination_station', models.CharField(max_length=256)),
                ('documents_number', models.CharField(max_length=50)),
                ('shipment_price', models.DecimalField(decimal_places=9, max_digits=16)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Cargo')),
                ('cargo_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.CargoState')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Contractor')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='ForwardVoucherExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=9, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='ForwardVoucherStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sending', models.DateField()),
                ('date_arrival_plan', models.DateField()),
                ('date_arrival_fact', models.DateField()),
                ('carrier_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='api.CarrierRequest')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='price',
            field=models.DecimalField(decimal_places=9, max_digits=16),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.ShipmentStatus'),
        ),
        migrations.AddField(
            model_name='forwardvoucherexpenses',
            name='additional_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AdditionalService'),
        ),
        migrations.AddField(
            model_name='forwardvoucherexpenses',
            name='forward_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ForwardVoucher'),
        ),
        migrations.AddField(
            model_name='forwardvoucher',
            name='expenses',
            field=models.ManyToManyField(through='api.ForwardVoucherExpenses', to='api.AdditionalService'),
        ),
        migrations.AddField(
            model_name='forwardvoucher',
            name='packaging_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.PackagingType'),
        ),
        migrations.AddField(
            model_name='forwardvoucher',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Contractor'),
        ),
        migrations.AddField(
            model_name='forwardvoucher',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Contractor'),
        ),
        migrations.AddField(
            model_name='forwardvoucher',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_vouchers', to='api.Shipment'),
        ),
        migrations.AddField(
            model_name='forwardvoucher',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.ParcelSize'),
        ),
        migrations.AddField(
            model_name='forwardvoucher',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.ForwardVoucherStatus'),
        ),
    ]
